In [2]:
import pandas as pd
import geopandas as gpd
import folium

# #1. 인사동 관광 경로

In [8]:
# 1. 인사동 경로 데이터 추출
tour_data_lab = pd.read_csv('data/종로구_인기관광지.csv', encoding='cp949')
data_extracted = tour_data_lab[tour_data_lab['주소'].str.contains('인사동')]
data_extracted = data_extracted[~data_extracted['분류'].str.contains('호텔')]
data_extracted.head()

    순위    관광지명                  주소    분류  합산 검색 수
28  29   안녕인사동    서울 종로구 인사동길 49-0   쇼핑몰    13906
75  76   경인미술관  서울 종로구 인사동10길 11-4  전시시설     4313
78  79  갤러리라메르   서울 종로구 인사동5길 26-0  전시시설     4172

# #2. 청계천 길 관광 경로

In [9]:
# 2. 청겨천 길 경로 데이터 추출
tour_list = pd.read_csv('data/tour_list.csv')
tour_list = tour_list.fillna(' ')
data_extracted = tour_list[tour_list['themeCategory'].str.contains('청계천')]
data_extracted = data_extracted.sort_values('mapX')
data_extracted.head(10)

,addr1,addr2,createdtime,langCheck,langCode,mapX,mapY,modifiedtime,themeCategory,tid,title,tlid,imageUrl
53,서울,종로구,2.020000e+13,1111,ko,126.977897,37.569174,2.020000e+13,청계천 다리,679,청계천,1568,
54,서울,종로구,2.020000e+13,1111,ko,126.979251,37.569078,2.020000e+13,청계천 다리,680,모전교,1572,
43,서울,종로구,2.020000e+13,1111,ko,126.981086,37.568937,2.020000e+13,청계천 다리,53,광통교,168,
55,서울,종로구,2.020000e+13,1111,ko,126.982738,37.568827,2.020000e+13,청계천 다리,683,광교,1576,
56,서울,종로구,2.020000e+13,1111,ko,126.985790,37.568301,2.020000e+13,청계천 다리,684,장통교,1580,
57,서울,종로구,2.020000e+13,1111,ko,126.987501,37.568105,2.020000e+13,청계천 다리,685,삼일교,1584,
45,서울,종로구,2.020000e+13,1111,ko,126.990173,37.568137,2.020000e+13,청계천 다리,55,수표교터,176,
58,서울,종로구,2.020000e+13,1111,ko,126.992359,37.568348,2.020000e+13,청계천 다리,687,관수교,1588,
59,서울,종로구,2.020000e+13,1111,ko,126.995087,37.568546,2.020000e+13,청계천 다리,688,세운교,1592,
60,서울,종로구,2.020000e+13,1111,ko,126.997911,37.568846,2.020000e+13,청계천 다리,689,배오개다리,1596,

# #3. 문화/전시 관광 경로

In [20]:
# 3.1. 종로구 인기관광지
tour_spot_popular = pd.read_csv('data/종로구_인기관광지.csv', encoding='cp949')
tour_spot_popular = tour_spot_popular[tour_spot_popular['분류'].str.contains('전시')]
del tour_spot_popular['합산 검색 수']
tour_spot_popular.head(15)

    순위          관광지명                  주소    분류  합산 검색 수
3    4    국립현대미술관서울관     서울 종로구 삼청로 30-0  전시시설   107493
15  16       서울역사박물관    서울 종로구 새문안로 55-0  전시시설    28113
17  18        청와대사랑채  서울 종로구 효자로13길 45-0  전시시설    22380
27  28  총회창립100주년기념관   서울 종로구 대학로3길 29-0  전시시설    14094
30  31        가나아트센터   서울 종로구 평창30길 28-0  전시시설    12684
31  32      국립어린이과학관   서울 종로구 창경궁로 215-0  전시시설    11565
33  34         서울미술관   서울 종로구 자하문로 231-0  전시시설    11140
34  35       국립민속박물관     서울 종로구 삼청로 37-0  전시시설    10979
35  36       국립고궁박물관     서울 종로구 효자로 12-0  전시시설    10673
43  44         국제갤러리     서울 종로구 삼청로 54-0  전시시설     8112
45  46       서울공예박물관    서울 종로구 율곡로3길 4-0  전시시설     7791
50  51         화정박물관     서울 종로구 평창8길 3-0  전시시설     7257
52  53     대한민국역사박물관   서울 종로구 세종대로 198-0  전시시설     6972
60  61        윤동주문학관   서울 종로구 창의문로 119-0  전시시설     5523
62  63         경찰박물관    서울 종로구 송월길 162-0  전시시설     5331

In [21]:
# 3.1. 종로구 중심관광지
tour_spot_main = pd.read_csv('data/종로구_중심관광지.csv', encoding='cp949')
tour_spot_main = tour_spot_main[tour_spot_main['분류'].str.contains('문화')]
tour_spot_main.head(15)

    순위            관광지명                  주소    분류
4    5     국립현대미술관/서울관     서울 종로구 삼청로 30-0  문화시설
9   10  서울특별시교육청/정독도서관   서울 종로구 북촌로5길 48-0  문화시설
14  15         서울역사박물관    서울 종로구 새문안로 55-0  문화시설
19  20          청와대사랑채  서울 종로구 효자로13길 45-0  문화시설
26  27         국립고궁박물관     서울 종로구 효자로 12-0  문화시설
27  28       그라운드시소/서촌  서울 종로구 자하문로6길 18-8  문화시설
30  31           서울미술관   서울 종로구 자하문로 231-0  문화시설
31  32          가나아트센터   서울 종로구 평창30길 28-0  문화시설
32  33         국립민속박물관     서울 종로구 삼청로 37-0  문화시설
33  34         서울공예박물관    서울 종로구 율곡로3길 4-0  문화시설
37  38  서울특별시교육청어린이도서관    서울 종로구 사직로9길 7-0  문화시설
38  39       대한민국역사박물관   서울 종로구 세종대로 198-0  문화시설
41  42           국제갤러리     서울 종로구 삼청로 54-0  문화시설
44  45          윤동주문학관   서울 종로구 창의문로 119-0  문화시설
46  47        국립어린이과학관   서울 종로구 창경궁로 215-0  문화시설

In [22]:
# 3.2. 전처리 : 주소 -> 경위도 좌표(Kakao API 이용)
import requests

# 3.2.1 인기 관광지 변환
address = tour_spot_popular['주소'].tolist()
mapX = []
mapY = []

for i in range(len(address)):
    REST_API_KEY = '80b269050cd58c9743d68720ddc84692'

    headers = {
        'Authorization': f"KakaoAK {REST_API_KEY}",
        'Content-Type': 'application/x-www-form-urlencoded',
    }

    data = f'query={address[i]}'

    response = requests.get('https://dapi.kakao.com/v2/local/search/address.json', headers=headers, data=data.encode('utf-8'))
    text = response.json()

    mapX.append(text['documents'][0]['x'])
    mapY.append(text['documents'][0]['y'])

tour_spot_popular['lat'] = mapY
tour_spot_popular['lon'] = mapX

tour_spot_popular.to_csv('data/tour_spot_popular.csv', encoding='utf-8', index=False)
tour_spot_popular.head(15)

,순위,관광지명,주소,분류,합산 검색 수,lat,lon
3,4,국립현대미술관서울관,서울 종로구 삼청로 30-0,전시시설,107493,37.5786280284849,126.980087994867
15,16,서울역사박물관,서울 종로구 새문안로 55-0,전시시설,28113,37.5704968494713,126.97107522045
17,18,청와대사랑채,서울 종로구 효자로13길 45-0,전시시설,22380,37.582544875368,126.973059283309
27,28,총회창립100주년기념관,서울 종로구 대학로3길 29-0,전시시설,14094,37.5744586423861,127.000669816963
30,31,가나아트센터,서울 종로구 평창30길 28-0,전시시설,12684,37.6121893924775,126.975179000169
31,32,국립어린이과학관,서울 종로구 창경궁로 215-0,전시시설,11565,37.5820319129511,126.99701568979
33,34,서울미술관,서울 종로구 자하문로 231-0,전시시설,11140,37.594702820251,126.963202630054
34,35,국립민속박물관,서울 종로구 삼청로 37-0,전시시설,10979,37.5794848231803,126.97876366569
35,36,국립고궁박물관,서울 종로구 효자로 12-0,전시시설,10673,37.5765916191985,126.974974825074
43,44,국제갤러리,서울 종로구 삼청로 54-0,전시시설,8112,37.5807206678387,126.98057390782
45,46,서울공예박물관,서울 종로구 율곡로3길 4-0,전시시설,7791,37.5766481740232,126.983533363501
50,51,화정박물관,서울 종로구 평창8길 3-0,전시시설,7257,37.6045448453703,126.966081861578
52,53,대한민국역사박물관,서울 종로구 세종대로 198-0,전시시설,6972,37.5737136067193,126.978339442463
60,61,윤동주문학관,서울 종로구 창의문로 119-0,전시시설,5523,37.592096942441,126.96706863952
62,63,경찰박물관,서울 종로구 송월길 162-0,전시시설,5331,37.5720572964048,126.962196007118

In [23]:
# 3.2.2 중심 관광지 변환
from cmath import nan


address = tour_spot_main['주소'].tolist()
mapX = []
mapY = []

for i in range(len(address)):
    REST_API_KEY = '80b269050cd58c9743d68720ddc84692'

    headers = {
        'Authorization': f"KakaoAK {REST_API_KEY}",
        'Content-Type': 'application/x-www-form-urlencoded',
    }

    data = f'query={address[i]}'

    response = requests.get('https://dapi.kakao.com/v2/local/search/address.json', headers=headers, data=data.encode('utf-8'))
    text = response.json()

    try:
        mapX.append(text['documents'][0]['x']) 
    except Exception:
        mapX.append(nan)

    try:
        mapY.append(text['documents'][0]['y'])
    except Exception:
        mapY.append(nan)

tour_spot_main['lat'] = mapY
tour_spot_main['lon'] = mapX

tour_spot_main.dropna()
tour_spot_main.to_csv('data/tour_spot_main.csv', encoding='utf-8', index=False)
tour_spot_main.head(15)

,순위,관광지명,주소,분류,lat,lon
4,5,국립현대미술관/서울관,서울 종로구 삼청로 30-0,문화시설,37.5786280284849,126.980087994867
9,10,서울특별시교육청/정독도서관,서울 종로구 북촌로5길 48-0,문화시설,37.5812654545612,126.983870059299
14,15,서울역사박물관,서울 종로구 새문안로 55-0,문화시설,37.5704968494713,126.97107522045
19,20,청와대사랑채,서울 종로구 효자로13길 45-0,문화시설,37.582544875368,126.973059283309
26,27,국립고궁박물관,서울 종로구 효자로 12-0,문화시설,37.5765916191985,126.974974825074
27,28,그라운드시소/서촌,서울 종로구 자하문로6길 18-8,문화시설,37.577840393396,126.972916073118
30,31,서울미술관,서울 종로구 자하문로 231-0,문화시설,37.594702820251,126.963202630054
31,32,가나아트센터,서울 종로구 평창30길 28-0,문화시설,37.6121893924775,126.975179000169
32,33,국립민속박물관,서울 종로구 삼청로 37-0,문화시설,37.5794848231803,126.97876366569
33,34,서울공예박물관,서울 종로구 율곡로3길 4-0,문화시설,37.5766481740232,126.983533363501
37,38,서울특별시교육청어린이도서관,서울 종로구 사직로9길 7-0,문화시설,37.5762858214854,126.968231878405
38,39,대한민국역사박물관,서울 종로구 세종대로 198-0,문화시설,37.5737136067193,126.978339442463
41,42,국제갤러리,서울 종로구 삼청로 54-0,문화시설,37.5807206678387,126.98057390782
44,45,윤동주문학관,서울 종로구 창의문로 119-0,문화시설,37.592096942441,126.96706863952
46,47,국립어린이과학관,서울 종로구 창경궁로 215-0,문화시설,37.5820319129511,126.99701568979

In [25]:
# 3.3 인기, 중심 관광지 병합
tour_spot_merge = pd.concat([tour_spot_main, tour_spot_popular])
tour_spot_merge.to_csv('data/tour_spot_merge.csv', encoding='utf-8', index=False)
tour_spot_merge.head()

,순위,관광지명,주소,분류,lat,lon
4,5,국립현대미술관/서울관,서울 종로구 삼청로 30-0,문화시설,37.5786280284849,126.980087994867
9,10,서울특별시교육청/정독도서관,서울 종로구 북촌로5길 48-0,문화시설,37.5812654545612,126.983870059299
14,15,서울역사박물관,서울 종로구 새문안로 55-0,문화시설,37.5704968494713,126.97107522045
19,20,청와대사랑채,서울 종로구 효자로13길 45-0,문화시설,37.582544875368,126.973059283309
26,27,국립고궁박물관,서울 종로구 효자로 12-0,문화시설,37.5765916191985,126.974974825074

In [26]:
# 3.4 기존 tour_spo_algo 기반 경로 추천
result = pd.read_csv('data/result_third.csv')
result.head()

,o_idx,o_name,o_lat,o_lon,d_idx,d_name,d_lat,d_lon
0,1,국립현대미술관,37.578628,126.980088,2,서울공예박물관,37.576648,126.983533
1,2,서울공예박물관,37.576648,126.983533,3,PKM갤러리,37.584092,126.980082
2,3,PKM갤러리,37.584092,126.980082,4,국립고궁박물관,37.576592,126.974975
3,4,국립고궁박물관,37.576592,126.974975,5,서울역사박물관,37.570497,126.971075
4,5,서울역사박물관,37.570497,126.971075,6,대한민국역사박물관,37.573714,126.978339

# #4. 북촌 골목여행, 서촌 골목여행 관광 경로

In [36]:
# 3.1 Tour API 관광지 추출 (북촌 골목여행, 서촌 골목여행)
tour_spot_road = pd.read_csv('data/tour_list.csv')
tour_spot_road = tour_spot_road.fillna(' ')
tour_spot_road = tour_spot_road[tour_spot_road['themeCategory'].str.contains('골목')]
tour_spot_road.rename(columns = {'mapX':'lon','mapY':'lat'},inplace=True)
tour_spot_road = tour_spot_road.sort_values('tid')
tour_spot_road.to_csv('data/result_forth.csv')
tour_spot_road.head(20)

,addr1,addr2,createdtime,langCheck,langCode,lon,lat,modifiedtime,themeCategory,tid,title,tlid,imageUrl
22,서울,종로구,2.020000e+13,1111,ko,126.986042,37.577253,2.020000e+13,북촌 골목여행,69,북촌,229,
23,서울,종로구,2.020000e+13,1111,ko,126.982317,37.578042,2.020000e+13,북촌 골목여행,70,감고당길,233,
24,서울,종로구,2.020000e+13,1111,ko,126.982999,37.581026,2.020000e+13,북촌 골목여행,71,정독도서관,237,
25,서울,종로구,2.020000e+13,1111,ko,126.986750,37.580688,2.020000e+13,북촌 골목여행,72,계동길,241,
26,서울,종로구,2.020000e+13,1111,ko,126.982051,37.584837,2.020000e+13,북촌 골목여행,73,삼청동길,245,
27,서울,종로구,2.020000e+13,1111,ko,126.988919,37.583820,2.020000e+13,북촌 골목여행,74,원서동 빨래터,249,
28,서울,종로구,2.020000e+13,1111,ko,126.988941,37.583087,2.020000e+13,북촌 골목여행,75,고희동 가옥(고희동미술관),250,
29,서울,종로구,2.020000e+13,1111,ko,126.984121,37.580889,2.020000e+13,북촌 골목여행,76,백인제가옥,251,
76,서울,중구,2.020000e+13,1111,ko,126.974588,37.564789,2.020000e+13,정동 골목여행,999,덕수궁 돌담길,2001,
77,서울,중구,2.020000e+13,1111,ko,126.973790,37.564055,2.020000e+13,정동 골목여행,1000,서울시립미술관,2002,
78,서울,중구,2.020000e+13,1111,ko,126.972610,37.563987,2.020000e+13,정동 골목여행,1001,배재학당 역사박물관,2003,
79,서울,중구,2.020000e+13,1111,ko,126.972438,37.565373,2.020000e+13,정동 골목여행,1002,정동 제일교회,2004,
80,서울,중구,2.020000e+13,1111,ko,126.973408,37.565197,2.020000e+13,정동 골목여행,1003,정동로터리,2005,
81,서울,중구,2.020000e+13,1111,ko,126.972804,37.565964,2.020000e+13,정동 골목여행,1004,정동극장,2006,
82,서울,중구,2.020000e+13,1111,ko,126.972481,37.566623,2.020000e+13,정동 골목여행,1005,덕수궁 중명전,2007,
83,서울,중구,2.020000e+13,1111,ko,126.971387,37.566164,2.020000e+13,정동 골목여행,1006,이화학당,2008,
84,서울,중구,2.020000e+13,1111,ko,126.971548,37.567899,2.020000e+13,정동 골목여행,1007,구 러시아공사관 터(정동공원),2009,
85,서울,중구,2.020000e+13,1111,ko,126.972996,37.567023,2.020000e+13,정동 골목여행,1008,하비브 하우스,2010,
86,서울,중구,2.020000e+13,1111,ko,126.973751,37.567864,2.020000e+13,정동 골목여행,1009,구세군 중앙회관,2011,
87,서울,중구,2.020000e+13,1111,ko,126.976059,37.567087,2.020000e+13,정동 골목여행,1010,대한성공회 서울 주교좌성당,2012,